app/yaspi.mvc/Controllers/ConnectorController.cs
using System.Net;
using Microsoft.AspNetCore.Mvc;
using yaspi.mvc.Code;
using yaspi.mvc.Models;
using System.Text.Json;
using yaspi.common.OAuth;
using Microsoft.AspNetCore.Authorization;
using yaspi.integration.facebook;
using yaspi.integration.twitter;

namespace yaspi.mvc.Controllers;

[Authorize]
public class ConnectorController : YaspiController
{
    private readonly ILogger<ConnectorController> _logger;
    private readonly IConnectionManager _connectionManagerService;
    private readonly IConfiguration _configuration;
    private readonly IFacebookApiService _facebookApiService;
    private readonly ITwitterApiService _twitterApiService;
    public ConnectorController(ILogger<ConnectorController> logger, IConnectionManager connectionManagerService,
                            IConfiguration configuration, 
                            IFacebookApiService facebookApiService, ITwitterApiService twitterApiService)
    {
        _logger = logger;
        _connectionManagerService = connectionManagerService;
        _configuration = configuration;
        _facebookApiService = facebookApiService;
        _twitterApiService = twitterApiService;
    }

    public IActionResult Index(string connector)
    {

        var value = _connectionManagerService.GetConnectorViewModel(connector);
        return View(value);
    }
    [HttpGet]
    public IActionResult Connect()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Connect(string submit, int connectorId, string connectorName)
    {
        return Redirect("/Home/ListConnectors");
    }


    [HttpGet]
    public IActionResult ConnectTwitter()
    {
        Request.Query.TryGetValue("code", out var code);
        Request.Query.TryGetValue("state", out var stateIn);
        Request.Query.TryGetValue("error", out var error);

        if (error == "access_denied")
        {
            return Redirect("/Home/ListConnectors");
        }
        if (string.IsNullOrWhiteSpace(code) && string.IsNullOrWhiteSpace(stateIn)) // initial state
        {
            var url = _twitterApiService.GetAuthRequestUrl();
            return Redirect(url);
        }
        else if (stateIn == "step1")
        {
            var config = _twitterApiService.GetConnectionData(code);
            string username = GetUserName();
            _connectionManagerService.Connect(username, 1, config);
        }
        return View();
    }

    public IActionResult ConnectionSettings(int id)
    {
        YaspiConnectionViewModel value = _connectionManagerService.GetConnectionViewModel(id);
        return View(value);
    }

    [HttpGet]
    public IActionResult ConnectFacebook()
    {
        Request.Query.TryGetValue("code", out var code);
        Request.Query.TryGetValue("state", out var stateIn);
        Request.Query.TryGetValue("error", out var error);
        string client_id = _configuration.GetValue<string>("Facebook:app_id");
        string redirect_uri = _configuration.GetValue<string>("Facebook:redirect_url");
        string token_url = _configuration.GetValue<string>("Facebook:token_url");
        string client_secret = _configuration.GetValue<string>("Facebook:app_secret");

        if (error == "access_denied")
        {
            return Redirect("/Home/ListConnectors");
        }
        if (string.IsNullOrWhiteSpace(code) && string.IsNullOrWhiteSpace(stateIn)) // initial state
        {
            string url = _facebookApiService.GetAuthRequestUrl();
            return Redirect(url);
        }
        else if (stateIn == "step1") // 
        {
            WebClient wc = new WebClient();
            wc.Headers.Add("Content-Type", "application/x-www-form-urlencoded");
            string parameters = $"client_id={client_id}&redirect_uri={redirect_uri}&client_secret={client_secret}&code={code}";
            string ret = null;
            try { ret = wc.UploadString(token_url, parameters); }
            catch (WebException e)
            {// this can happen when user uses <back> button in browser
                using (var reader = new StreamReader(e.Response.GetResponseStream()))
                {
                    string err = reader.ReadToEnd();
                }
            }
            System.Console.WriteLine(ret);
            var d = JsonSerializer.Deserialize<OauthBearer>(ret);
            var data = _facebookApiService.GetConnectionData(d.access_token);
            KeyValuePair<string, string>[] tokenInfo = new KeyValuePair<string, string>[]
            {
                new KeyValuePair<string, string>("access_token", d.access_token),
                new KeyValuePair<string, string>("expires_in", d.expires_in.ToString()),
                new KeyValuePair<string, string>("token_type", d.token_type),
            };
            List<KeyValuePair<string, string>> config = new List<KeyValuePair<string, string>>();
            config.AddRange(tokenInfo);
            config.AddRange(data);
            string username = GetUserName();
            _connectionManagerService.Connect(username, 2, config.ToArray());
        }
        return View();
    }

    [HttpPost]
    public IActionResult ConnectFacebook(string x)
    {
        return View();
    }

    [HttpPost]
    public IActionResult ConnectTwitter(string x)
    {
        HttpRequest request = HttpContext.Request;
        string username = GetUserName();
        return Redirect("/Home/ListConnectors");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Manage()
    {
        List<YaspiConnectionViewModel> connections = _connectionManagerService.GetAllUserConnections(GetUserName());
        var model = new ManageVewModel();
        model.Connections = connections;
        return View(model);
    }

    [HttpPost]
    public IActionResult Manage(ManageVewModel model)
    {
        _connectionManagerService.ToggleUserConnectionActiveById(GetUserName(), model.Toggle);
        model.Connections = _connectionManagerService.GetAllUserConnections(GetUserName());
        return View(model);
    }
}

app/yaspi.mvc/Views/Shared/_ErrorPartial.cshtml
@model string


<div class="alert alert-danger" id="result-message" role="alert">
  @Model
</div>

app/yaspi.mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - yaspi.mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/yaspi.mvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">YASPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="ListConnectors">Connect</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Connector"
                                asp-action="Manage">Manage</a>
                        </li>

                        <li class="nav-item">
                            <a id="messages-tab" class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Messages">Messages</a>
                        </li>
                        <li class="nav-item">
                            <a id="messages-tab" class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="WebApi">API</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - yaspi.mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

app/yaspi.mvc/Views/Shared/_SuccessPartial.cshtml
@model string


<div class="alert alert-success" id="result-message" role="alert">
  @Model
</div>